[build]
command = "cd Project/backend && npm install"

[start]
command = "cd Project/backend && node server.js"

[deploy]
numReplicas = 1
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
